name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  # 在提合并请求的时候触发
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  codeReview:
    runs-on: ubuntu-latest
    steps:
      - name: GPT代码逻辑检查
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_ENDPOINT: https://api.groq.com/openai/v1
          MODEL: llama-3.1-70b-versatile
          LANGUAGE: Chinese
